import { LevelConfig } from '../../types/level-config';

export const LEVEL_4: LevelConfig[] = [
  // base start
  { xStart: 22, yStart: 46, xCellsAmount: 2, yCellsAmount: 6, type: 'default' },
  { xStart: 24, yStart: 46, xCellsAmount: 4, yCellsAmount: 2, type: 'default' },
  { xStart: 28, yStart: 46, xCellsAmount: 2, yCellsAmount: 6, type: 'default' },
  { xStart: 4, yStart: 0, xCellsAmount: 8, yCellsAmount: 4, type: 'gross' },
  { xStart: 0, yStart: 4, xCellsAmount: 8, yCellsAmount: 4, type: 'gross' },
  { xStart: 44, yStart: 0, xCellsAmount: 4, yCellsAmount: 4, type: 'gross' },
  { xStart: 48, yStart: 4, xCellsAmount: 4, yCellsAmount: 4, type: 'gross' },
  { xStart: 0, yStart: 8, xCellsAmount: 4, yCellsAmount: 4, type: 'gross' },
  { xStart: 0, yStart: 12, xCellsAmount: 4, yCellsAmount: 2, type: 'stone' },
  { xStart: 48, yStart: 8, xCellsAmount: 4, yCellsAmount: 2, type: 'stone' },
  { xStart: 0, yStart: 48, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 48, yStart: 48, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 0, yStart: 44, xCellsAmount: 4, yCellsAmount: 4, type: 'gross' },
  { xStart: 4, yStart: 48, xCellsAmount: 4, yCellsAmount: 4, type: 'gross' },
  { xStart: 40, yStart: 48, xCellsAmount: 8, yCellsAmount: 4, type: 'gross' },
  { xStart: 48, yStart: 40, xCellsAmount: 4, yCellsAmount: 4, type: 'gross' },
  { xStart: 44, yStart: 44, xCellsAmount: 8, yCellsAmount: 4, type: 'gross' },
  { xStart: 4, yStart: 40, xCellsAmount: 8, yCellsAmount: 4, type: 'default' },
  { xStart: 8, yStart: 44, xCellsAmount: 8, yCellsAmount: 2, type: 'default' },
  { xStart: 12, yStart: 42, xCellsAmount: 4, yCellsAmount: 2, type: 'default' },

  { xStart: 36, yStart: 40, xCellsAmount: 8, yCellsAmount: 4, type: 'default' },
  { xStart: 32, yStart: 44, xCellsAmount: 8, yCellsAmount: 2, type: 'default' },
  { xStart: 32, yStart: 42, xCellsAmount: 4, yCellsAmount: 2, type: 'default' },
  { xStart: 0, yStart: 20, xCellsAmount: 4, yCellsAmount: 4, type: 'water' },
  { xStart: 44, yStart: 24, xCellsAmount: 8, yCellsAmount: 4, type: 'water' },
  { xStart: 20, yStart: 4, xCellsAmount: 8, yCellsAmount: 2, type: 'default' },
  { xStart: 16, yStart: 6, xCellsAmount: 20, yCellsAmount: 2, type: 'default' },
  { xStart: 14, yStart: 8, xCellsAmount: 26, yCellsAmount: 4, type: 'default' },
  { xStart: 40, yStart: 10, xCellsAmount: 4, yCellsAmount: 2, type: 'default' },
  { xStart: 12, yStart: 12, xCellsAmount: 32, yCellsAmount: 4, type: 'default' },
  { xStart: 10, yStart: 16, xCellsAmount: 6, yCellsAmount: 2, type: 'default' },
  { xStart: 10, yStart: 18, xCellsAmount: 2, yCellsAmount: 6, type: 'default' },
  { xStart: 8, yStart: 24, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 16, yStart: 26, xCellsAmount: 8, yCellsAmount: 2, type: 'default' },
  { xStart: 8, yStart: 28, xCellsAmount: 32, yCellsAmount: 4, type: 'default' },
  { xStart: 6, yStart: 32, xCellsAmount: 36, yCellsAmount: 4, type: 'default' },
  { xStart: 4, yStart: 36, xCellsAmount: 40, yCellsAmount: 2, type: 'default' },
  { xStart: 12, yStart: 38, xCellsAmount: 24, yCellsAmount: 2, type: 'default' },
  { xStart: 16, yStart: 40, xCellsAmount: 16, yCellsAmount: 2, type: 'default' },
  { xStart: 20, yStart: 42, xCellsAmount: 8, yCellsAmount: 2, type: 'default' },

  { xStart: 16, yStart: 20, xCellsAmount: 2 ,yCellsAmount: 4, type: 'stone' },
  { xStart: 24, yStart: 20, xCellsAmount: 2 ,yCellsAmount: 4, type: 'stone' },

  { xStart: 28, yStart: 16, xCellsAmount: 10, yCellsAmount: 2, type: 'default' },
  { xStart: 32, yStart: 18, xCellsAmount: 6, yCellsAmount: 12, type: 'default' },
  { xStart: 38, yStart: 16, xCellsAmount: 2, yCellsAmount: 4, type: 'default' },
  { xStart: 44, yStart: 12, xCellsAmount: 2, yCellsAmount: 8, type: 'default' },
];
