import { LevelConfig } from '../../types/level-config';

export const LEVEL_2: LevelConfig[] = [
  // base start
  { xStart: 22, yStart: 46, xCellsAmount: 2, yCellsAmount: 6, type: 'default' },
  { xStart: 24, yStart: 46, xCellsAmount: 4, yCellsAmount: 2, type: 'default' },
  { xStart: 28, yStart: 46, xCellsAmount: 2, yCellsAmount: 6, type: 'default' },
  // base end
  { xStart: 4, yStart: 4, xCellsAmount: 4, yCellsAmount: 8, type: 'default' },
  { xStart: 12, yStart: 12, xCellsAmount: 4, yCellsAmount: 8, type: 'default' },
  { xStart: 24, yStart: 8, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 28, yStart: 4, xCellsAmount: 4, yCellsAmount: 8, type: 'default' },
  { xStart: 36, yStart: 4, xCellsAmount: 4, yCellsAmount: 8, type: 'default' },
  { xStart: 44, yStart: 4, xCellsAmount: 4, yCellsAmount: 8, type: 'default' },
  { xStart: 36, yStart: 16, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 44, yStart: 16, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 20, yStart: 20, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 4, yStart: 24, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 8, yStart: 24, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 12, yStart: 24, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 4, yStart: 32, xCellsAmount: 4, yCellsAmount: 20, type: 'default' },
  { xStart: 12, yStart: 36, xCellsAmount: 4, yCellsAmount: 8, type: 'default' },
  { xStart: 12, yStart: 48, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 20, yStart: 28, xCellsAmount: 4, yCellsAmount: 16, type: 'default' },
  { xStart: 24, yStart: 36, xCellsAmount: 4, yCellsAmount: 8, type: 'default' },
  { xStart: 28, yStart: 28, xCellsAmount: 4, yCellsAmount: 16, type: 'default' },
  { xStart: 36, yStart: 28, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 44, yStart: 24, xCellsAmount: 4, yCellsAmount: 16, type: 'default' },
  { xStart: 36, yStart: 36, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 36, yStart: 44, xCellsAmount: 4, yCellsAmount: 8, type: 'default' },
  { xStart: 40, yStart: 48, xCellsAmount: 4, yCellsAmount: 4, type: 'default' },
  { xStart: 44, yStart: 44, xCellsAmount: 4, yCellsAmount: 8, type: 'default' },
  { xStart: 12, yStart: 0, xCellsAmount: 4, yCellsAmount: 8, type: 'stone' },
  { xStart: 28, yStart: 0, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 40, yStart: 8, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 36, yStart: 12, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 48, yStart: 16, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 0, yStart: 32, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 12, yStart: 28, xCellsAmount: 4, yCellsAmount: 8, type: 'stone' },
  { xStart: 24, yStart: 16, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 32, yStart: 20, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 40, yStart: 36, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 28, yStart: 24, xCellsAmount: 4, yCellsAmount: 4, type: 'stone' },
  { xStart: 0, yStart: 16, xCellsAmount: 4, yCellsAmount: 8, type: 'gross' },
  { xStart: 4, yStart: 20, xCellsAmount: 4, yCellsAmount: 4, type: 'gross' },
  { xStart: 40, yStart: 16, xCellsAmount: 4, yCellsAmount: 12, type: 'gross' },
  { xStart: 16, yStart: 24, xCellsAmount: 4, yCellsAmount: 8, type: 'gross' },
  { xStart: 20, yStart: 24, xCellsAmount: 4, yCellsAmount: 4, type: 'gross' },
  { xStart: 24, yStart: 24, xCellsAmount: 4, yCellsAmount: 4, type: 'gross' },
];
